# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    RiskType = apps.get_model("britecoreapp", "RiskType")
    RiskType.objects.using(db_alias).bulk_create([
        RiskType(name="Automobile"),
    ])
    rt = RiskType.objects.using(db_alias).get(name="Automobile")
    RiskTypeField = apps.get_model("britecoreapp", "RiskTypeField")
    RiskTypeField.objects.using(db_alias).bulk_create([
        RiskTypeField(risk_type_id=rt.id, name="Make/Model", field_type="TEXT"),
        RiskTypeField(risk_type_id=rt.id, name="Number of Insured Drivers", field_type="NUMBER"),
        RiskTypeField(risk_type_id=rt.id, name="Registration Date", field_type="DATE"),
        RiskTypeField(risk_type_id=rt.id, name="Registration State", field_type="ENUM"),
    ])
    rtf = RiskTypeField.objects.using(db_alias).get(name="Registration State")
    RiskTypeFieldOption = apps.get_model("britecoreapp", "RiskTypeFieldOption")
    RiskTypeFieldOption.objects.using(db_alias).bulk_create([
        RiskTypeFieldOption(risk_type_field_id=rtf.id, option_text="Florida"),
        RiskTypeFieldOption(risk_type_field_id=rtf.id, option_text="Georgia"),
        RiskTypeFieldOption(risk_type_field_id=rtf.id, option_text="Alabama"),
    ])

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RiskTypeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('ENUM', 'Enum')], default='TEXT', max_length=6)),
                ('risk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='britecoreapp.RiskType')),
            ],
        ),
        migrations.CreateModel(
            name='RiskTypeFieldOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200)),
                ('risk_type_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='britecoreapp.RiskTypeField')),
            ],
        ),
        migrations.RunPython(forwards_func),
    ]
